title: ACT-IAC Blockchain WG
description: Agendas, case studies, and contribution surfaces
markdown: kramdown
permalink: pretty
exclude:
  - _assets
  - node_modules

collections:
  meetings:
    output: true
    permalink: /meetings/:title/

defaults:
  - scope:
      path: ""
      type: meetings
    values:
      layout: meeting
